### ISSUE TITLE
support "Accept-Encoding: gzip, deflate"

### ISSUE THREAD

**Issue by bagder** [bagder/h2c#1]
... which should make curl use `--compressed`, even if that might not be a 100% match.

**Comment by divinity76** [comment]
For what it's worth, several other "curl converters" I've tried gets this wrong, giving the "accept-encoding" header but not --compressed / CURLOPT_ENCODING

**Comment by divinity76** [comment]
(and for the record, I support the --encoding method, even at the cost of possibly not being a 100% match... And GitHub seems to be having problems right now, not letting me edit my previous message, I'll try again later)

**Comment by bagder** [comment]
Yeah,  I think I got the Firefox devtools team to fix that bug and I don't remember if Chrome's "copy as curl" also has that flaw...

**Comment by bagder** [comment]
Implemented!
