### ISSUE TITLE
[Request] Publish the latest (stable) commit to GitHub release

### ISSUE THREAD

**Issue by tddschn** [bagder/h2c#14]
I think `h2c` is a useful and cool tool and would like to [included it](https://github.com/Homebrew/homebrew-core/pull/83757) as an official [Homebrew](https://brew.sh) package, so that people on macOS can install it with a single command `brew install h2c`.

However, h2c does not have any tagged releases, and is [not acceptable](https://github.com/Homebrew/homebrew-core/pull/83757#discussion_r693486088) in Homebrew/core per [homebrew policy](https://docs.brew.sh/Acceptable-Formulae#stable-versions).

Can you consider publishing the latest (stable) commit to GitHub release? Thanks!

**Comment by bagder** [comment]
Will do!

**Comment by bagder** [comment]
Done!

**Comment by tddschn** [comment]
Thank you Daniel! :)
