### ISSUE TITLE
Wrong output when parsing parameters in multipart form

### ISSUE THREAD

**Issue by salty-horse** [bagder/h2c#4]
When several form parameters are provided, the output from h2c is garbled.

This curl command:
`curl --form ONE=1 --form TWO=2 --form THREE=3 http://localhost:8000`

Performs this request:
```
POST / HTTP/1.1
Host: localhost:8000
User-Agent: curl/7.47.0
Accept: */*
Content-Length: 327
Expect: 100-continue
Content-Type: multipart/form-data; boundary=------------------------48e1b0f105811e87

--------------------------48e1b0f105811e87
Content-Disposition: form-data; name="ONE"

1
--------------------------48e1b0f105811e87
Content-Disposition: form-data; name="TWO"

2
--------------------------48e1b0f105811e87
Content-Disposition: form-data; name="THREE"

3
--------------------------48e1b0f105811e87--
```

Which h2c outputs as:
```
curl --http1.1 --user-agent "curl/7.47.0" --form ONE=1 --form TWO=1
2 --form THREE=1
2
3 https://localhost:8000/
```

Note that the value of the form fields keeps accumulating instead of resetting. `TWO`'s value is `1\n2` and `THREE`'s value is `1\n2\n3`.

**Comment by bagder** [comment]
Regarding your last point, the page already says:
> The generated command line assumes a HTTPS site and generates such a URL. There is typically nothing in the request that tells if HTTPS or HTTP was used. 

I'll work on the bug...

**Comment by salty-horse** [comment]
Sorry, I realized it later and edited the last sentences.
Please have a look at the latest report because I added some information.

**Comment by bagder** [comment]
Fixed!
