### ISSUE TITLE
wrap url in (double/single) quotes

### ISSUE THREAD

**Issue by kleinron** [bagder/h2c#7]
If the URL contains an ampersand (`&`) it is interpreted as "run in a different process" in the command line shell.
Wrapping it in quotes might be helpful.

**Comment by bagder** [comment]
:+1:

**Comment by bagder** [comment]
Thanks!

**Comment by kleinron** [comment]
that was fast :)

**Comment by bagder** [comment]
It was also a very easy fix... =)
