### ISSUE TITLE
Generated URL always has "https" scheme

### ISSUE THREAD

**Issue by kleinron** [bagder/h2c#8]
Current behaviour:
Seems that any input generates "https" output

Desired:
User may indicate which scheme they want in the generated URL: http/https.

**Comment by jumo-sballing** [comment]
Same problem for me.

**Comment by bagder** [comment]
So you'd like to see a command line switch (and perhaps a button on the web page) to change the URL to plain old `http:` ?

**Comment by kleinron** [comment]
@bagder that would be great, yes :ok_hand:
